### ISSUE TITLE
Postcode.nl API

### ISSUE THREAD

**Issue by mjepronk** [hootnot/postcode-api-wrapper#12]
We've got the following e-mail from postcode.nl:

---

Dear client,

You have been successfully using our API for many years - thank you for that! Three years ago we updated the recommended way of using our API - and this change will also apply to all clients from 16 January onwards.

Please forward this message to your technical party, so that they can perform testing to ensure everything continues to work correctly.

**Planned change**

Traffic for the api.postcode.nl domain will be handled via Cloudflare starging 16 January. Our other domain api.postcode.eu already uses Cloudflare. We are making this change to better guarantee the capacity and availability of our services.

Our records show that your account currently calls the address API using the api.postcode.nl domain.

In the following cases, this change will impact the use of our API:

If you restrict outgoing connections in a firewall, you should be aware that Cloudflare IP’s <https://www.cloudflare.com/en-gb/ips/> will be used.

If you run outdated software, bear in mind that TLS 1.0 and TLS 1.1 will no longer be supported.

**Testing in advance**

We advise you to test whether your API implementation will continue to work correctly. In order to test you can migrate to the api.postcode.eu domain. To do this, modify API requests as follows:

api.postcode.nl/rest/addresses/2012es/30

api.postcode.nl/rest/addresses/postcode/2012es/

become: api.postcode.eu/nl/v1/addresses/postcode/2012es/30

api.postcode.nl/rest/postcode-ranges/postcode/2012es

becomes: api.postcode.eu/nl/v1/postcode-ranges/postcode/2012es

No further changes to your implementation are necessary! You can continue using the new domain from now on.

**Questions**

If you have any questions regarding this change we are happy to help you! You can simply reply to this message. You can also consult our documentation <https://developer.postcode.eu/documentation>.

**Comment by mjepronk** [comment]
@hootnot If you're interested, I'll prepare a PR to make the required changes.

**Comment by hootnot** [comment]
Hi,

please feel free to do so.

**Comment by Floordeweijer** [comment]
Hi @mjepronk,

I'm running into the same issue. Did you find the time to create a PR?

Thank you in advance for your response,

Floor

**Comment by mjepronk** [comment]
Hi Floor,
No, I'm sorry, shorty after posting m'y comment above I've discovered that our subscription expired and my client had no interest in renewing it. So I dropped the API from our project.
Should be a trivial change tough.
Matthias

**Comment by floorfabrique** [comment]
Hi @hootnot,

I've created a PR with the  required changes.

**Comment by hootnot** [comment]
@Floordeweijer : Thx!, merged the PR
